# Parámetros más importantes:
# ========================================================
# Tamaño de los datos de entrada:
# - in_s_channels: número de coordenadas escalares (en este caso, 1 para el thr, 3 si se usa one-hot encoding de thr1, thr2, thr3)
# - hidden_s_channels y hidden_mv_channels: "neuronas" del modelo.
# ========================================================
# Para el decoder:
# out_s_channels debe ser igual a in_s_channels del encoder para que el modelo pueda reconstruir la entrada original.
# Se asegurará en el código.



encoder:
    "hidden_mv_channels": 32 # Número de dimensiones internas (más grande, más "capacidad")
    "hidden_s_channels": 256 # Número de dimensiones internas (más grande, más "capacidad")
    "num_blocks": 4 # Número de bloques de atención (más bloques, más profundidad, pero más difícil de entrenar)
    "in_s_channels": 1 # Número de coordenadas "escalares" -> Nth (si es uno, sería 1, y si es one-hot de 3 clases, sería 3)
    "in_mv_channels": 1 # no tocar
    "out_mv_channels": 1 # no tocar
    "dropout": 0.
    "out_s_channels": 64 # Número de dimensiones de salida para la parte escalar (más grande, más capacidad, pero más difícil de entrenar) 
aggregation:
    "type": "mean" # Tipo de agregación para el paso de agregación (mean, max, sum, etc.)
decoder:
  "hidden_mv_channels": 32 # Número de dimensiones internas (más grande, más "capacidad")
  "hidden_s_channels": 256 # Número de dimensiones internas (más grande, más "capacidad")
  "num_blocks": 4 # Número de bloques de atención (más bloques, más profundidad, pero más difícil de entrenar)
  "in_s_channels": 128 # Tamaño de la representación latente interna.
  "in_mv_channels": 1 # no tocar
  "out_mv_channels": 1 # no tocar
  "dropout": 0.
  "out_s_channels": 1 